site_name: Unity Wiki
theme:
  name: material
  palette: 
    - scheme: slate  # Dark mode by default
      primary: blue
      accent: blue
  features:
    - navigation.tabs
    - search.suggest
    - content.code.copy
  markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.superfences

nav:
  - Home: index.md
  - Recruitment: recruitment.md
  - Raid Info:
      - Rules: raid-rules.md
      - Guides:
          - Molten Core: guides/raids/molten-core.md
          - Blackwing Lair: guides/raids/blackwing-lair.md
          - Temple of Ahn'Qiraj: guides/raids/temple-of-ahnqiraj.md
          - Naxxramas: guides/raids/naxxramas.md
      - Boss Guides: guides/boss-1.md